services:
  db:
    image: postgres:16
    container_name: p-log-db
    environment:
      POSTGRES_USER: pangho
      POSTGRES_PASSWORD: 6K4z4Kz25pUjQdd
      POSTGRES_DB: p_log
    ports:
      - '127.0.0.1:5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h 127.0.0.1 -U &&POSTGRES_USER -d &&POSTGRES_DB',
        ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pg_data:
